// js/i18n.js
// AquaTrack — simple bilingual toggle (Bahasa Melayu / English)
//
// How it works:
// - Any element that should be translatable gets a data-en="English text" attribute
//   in its HTML, while its normal text content stays as the Bahasa Melayu version.
// - This script injects a small 🇲🇾/🇬🇧 toggle button, fixed top-right, on every page.
// - Clicking it swaps each [data-en] element's text between its original (BM) and
//   the data-en value, and remembers the choice in localStorage so it stays
//   consistent as the user moves between screens.

(function () {
  const STORAGE_KEY = "aquatrack_lang";

  function injectToggle() {
    const toggle = document.createElement("div");
    toggle.className = "lang-toggle";
    toggle.innerHTML = `
      <button type="button" data-lang="ms">BM</button>
      <button type="button" data-lang="en">EN</button>
    `;
    document.body.appendChild(toggle);

    toggle.querySelectorAll("button").forEach((btn) => {
      btn.addEventListener("click", () => setLanguage(btn.dataset.lang));
    });
  }

  function applyLanguage(lang) {
    document.querySelectorAll("[data-en]").forEach((el) => {
      if (!el.dataset.ms) {
        // First run: remember the original Bahasa Melayu text before overwriting it.
        el.dataset.ms = el.textContent;
      }
      el.textContent = lang === "en" ? el.dataset.en : el.dataset.ms;
    });

    document.querySelectorAll(".lang-toggle button").forEach((btn) => {
      btn.classList.toggle("active", btn.dataset.lang === lang);
    });

    document.documentElement.setAttribute("lang", lang === "en" ? "en" : "ms");
  }

  function setLanguage(lang) {
    localStorage.setItem(STORAGE_KEY, lang);
    // Reload rather than live-patch: some content (charts, history summaries,
    // leaderboard rows) is generated by page-specific JS at load time, not
    // just static [data-en] text. Reloading guarantees everything on the
    // page — static and dynamic — reflects the chosen language consistently.
    window.location.reload();
  }

  // Ambient bubble field — the app's one deliberate motion signature.
  // A handful of slow-rising translucent circles, teal/coral mix, quiet
  // enough to sit behind content without distracting from it. Respects
  // prefers-reduced-motion via the global rule in styles.css.
  function injectAmbientBubbles() {
    if (document.querySelector(".bubble-field")) return;

    const field = document.createElement("div");
    field.className = "bubble-field";
    field.setAttribute("aria-hidden", "true");

    const BUBBLE_COUNT = 7;
    for (let i = 0; i < BUBBLE_COUNT; i++) {
      const bubble = document.createElement("div");
      const size = 14 + Math.round(Math.random() * 34); // 14px - 48px
      const left = Math.round(Math.random() * 100); // 0% - 100%
      const duration = 16 + Math.round(Math.random() * 14); // 16s - 30s
      const delay = -Math.round(Math.random() * duration); // negative = already mid-flight on load
      const drift = Math.round((Math.random() - 0.5) * 60); // -30px to 30px sideways sway

      bubble.className = "bubble" + (i % 3 === 0 ? " coral" : "");
      bubble.style.width = `${size}px`;
      bubble.style.height = `${size}px`;
      bubble.style.left = `${left}%`;
      bubble.style.animationDuration = `${duration}s`;
      bubble.style.animationDelay = `${delay}s`;
      bubble.style.setProperty("--bubble-drift", `${drift}px`);

      field.appendChild(bubble);
    }

    document.body.appendChild(field);
  }

  document.addEventListener("DOMContentLoaded", () => {
    injectToggle();
    const savedLang = localStorage.getItem(STORAGE_KEY) || "ms";
    applyLanguage(savedLang);
    injectAmbientBubbles();
  });
})();
